# Generated by Django 4.2 on 2023-04-10 14:00

import EmployeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0002_employee_delete_department_delete_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(
                default="post/ibro.jpg",
                upload_to=EmployeeApp.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
