# Generated by Django 4.2 on 2023-04-18 14:31

import EmployeeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0003_employee_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=EmployeeApp.models.upload_path
                    ),
                ),
            ],
        ),
    ]
